apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: flannel
    tier: node
  name: kube-flannel-cfg
  namespace: kube-system
data:
  my-key: my-value

kind: Pod
metadata:
  name: cmd-test
  labels:
    name: cmd-test
spec:
  containers:
  - name: cmd-test
    image: k8s.gcr.io/bushbox
    command: ["/bin/sh","-c", "env"]
    env:
      - name: SPEC_LEVEL_KEY
        valueFrom:
          configMapKeyRef:
            name: kube-flannel-cfg
            key: my-key