apiVersion: v1
kind: Pod
metadata:
  name: lineness-exec
  labels:
    name: lineness-exec
spec:
  containers:
  - name: lineness-exec
    image: k8s.grc.io/busybox:latest
    args:
      - /bin/sh
      - -c
      - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
 